120010036/README.txt

I added my genral info and interest in 120010036/README.txt
-Added name
-Added general information and research information

Added README.txt in 120010036 folder

---

13d070003/README.txt

Added a README.txt as suggested on Moodle with the same number of spaces and file structure.
Please accept the pull request.
First they ignore you.
Then they laugh at you.
Then they fight you.
And then you win.
- Story of Linux.

Pull Request 13d070003

---

13d170003/README.txt

I have added the readme file necessary for this assignment completion. Please accept this request and incorporate the additions

Adding README.txt for Assignment 1

---

13307r007/README.txt

Details of me are added which include name, course, dept, roll number, year and research interests
-Rakesh K K
13307R007

[Git Assignment] Conflict resolution 13307r007/README.txt

---

13d070058/README.txt

Added a README.txt as suggested on Moodle with the same  file structure.
Please accept the pull request.

Added README.txt for Roll-No 13d070058

---

110010013/README.txt

Added the required information asked

UPDATED README.txt

---

133079003/README.txt

I have added a new directory named from my roll-no and a README.txt file in it, containing my information.

Added my information, as requested, in a new README.txt.

---

133079022/README.txt

Completed the task given in Assignment1.
By Monika Sahai
133079022

Added a new directory containing README file

---

133070044/README.txt

I am sending this pull request as required to complete part-1 of assignment1,
roll no- 133070044

Adding my info in README.txt

---

133070016/README.txt

Sending a pull-request for the assignment 1 (17.1.2015).

Commiting README.txt file for first time

---

13d070064/README.txt

Please accept the pull request.

File added in my_branch

---

133079023/README.txt

README file added

---

133070091/README.txt

Adding README.txt for assignment 1. Please verify changes.

---

133079029/README.txt

This is README.txt for Assignment1_part1.

133079029_ Assignment1_part1.

---

07001019/README.txt

This is the pull request for assignment part 1 from Ashish Sharma,07001019

Assignment pull request/Ashish,07001019

---

110260028/README.txt

Git assignment part 1 submission by 110260028

Adding personal README for 110260028

---

110010012/README.txt

Made a directory 110010012 with README.txt in it

Initial commit for 1st assignment 

---

123079045/README.txt

My first pull request :) Happy soul learning git. Expecting feedback if things have gone wrong

Add my README.txt

---

123079008/README.txt

Adding my readme into Sdes rep (123079008)

---

134070020/README.txt

Submitted by : Deepak Anand
Roll No:134070020

File Readme.txt added by 134070020 as assignment 1

---

133070050/README.txt

Pull Request for adding my branch containing my student information for
AE 663.
Roll No: 133070050

Branch Commit for Roll No 133070050

---

133079024/README.txt

-README.txt file in the required format

Addign files for 1st Assignment

---

133074016/README.txt

Pull request by Roll no. 133074016

Adding README.txt by Roll no. 133074016

---

123079024/README.txt

Added the README.txt file for the first time

---

100010052/README.txt

Hello there, just introducing myself.

Add pritam's README.txt

---

134070012/README.txt

Assignment 1 by Chayan Bhawal Roll No-134070012

Adding directory with README.txt by 134070012

---

README.txt

110010038_assign-1

---

10d170007/README.txt
10d170007/README.txt~

Information supplied in required format

Adding README.txt for Pranav

---

110010017/README.txt
SDES2015/README.txt

Added 110010017 with README.txt

Commit after adding 110010017 folder with README.txt in new_branch

---

120010061/README.txt

Zaher Abdul Azeez -  Pull Request

Assignment

---

110010055/README.txt

added 110010055/README.txt with personal info.

ASHISH's FIRST COMMIT

---

README.txt

Revert "110010038_assign-1"
